version: "3.9"
services:
  db:
    image: mariadb:11
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASS}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASS}
    ports: ["3306:3306"]
    volumes: ["db_data:/var/lib/mysql"]

  api:
    build: ./infra/api
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      API_PORT: 4000
    ports: ["4000:4000"]
    depends_on: [db]

  web:
    build: ./infra/web
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:4000
    ports: ["3000:3000"]
    depends_on: [api]

  backend:
    build:
      context: ../../backend
    ports:
      - "9000:9000"
  
volumes:
  db_data:
